CREATE TABLE Users (
	id SERIAL PRIMARY KEY,
	username TEXT UNIQUE,
	password TEXT,
	teacher BOOLEAN
);

CREATE TABLE Courses (
	id SERIAL PRIMARY KEY,
	name TEXT,
	teacher_id INTEGER REFERENCES Users
);

CREATE TABLE Tasks (
	id SERIAL PRIMARY KEY,
	course_id INTEGER REFERENCES Courses
		ON DELETE CASCADE,
	question TEXT
);

CREATE TABLE Completions (
	id SERIAL PRIMARY KEY,
	student_id INTEGER REFERENCES Users,
	task_id INTEGER REFERENCES Tasks
		ON DELETE CASCADE
);

CREATE TABLE Choices (
	id SERIAL PRIMARY KEY,
	task_id INTEGER REFERENCES Tasks
		ON DELETE CASCADE,
	choice TEXT,
	correct BOOLEAN
);

CREATE TABLE Answers (
	id SERIAL PRIMARY KEY,
	student_id INTEGER REFERENCES Users,
	choice_id INTEGER REFERENCES Choices
		ON DELETE CASCADE
);
